# Generated by Django 4.1.5 on 2023-01-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='wallet_address',
            field=models.CharField(default='105fce3e78e73f60d8b138583de8cd38d613b38f7e1cbb8be721f775b274fba9', max_length=64),
        ),
    ]
