# Generated by Django 4.1.5 on 2023-01-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_alter_coin_quantity_alter_customuser_wallet_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('current_price', models.DecimalField(decimal_places=3, max_digits=20)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Coin',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='wallet_address',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='coins',
            field=models.ManyToManyField(to='wallets.transaction'),
        ),
    ]
